### ISSUE TITLE
Maybe here is a little bug for x[0] == 0

### ISSUE THREAD

**Issue by gujinqiangggs** [TheBlueMatt/shamirs#1]
In main.c:200

for (uint32_t i = 0; i < total_shares; i++) {
			int32_t j = 0;
			do {
				assert(fread(&x[i], sizeof(uint8_t), 1, random) == 1);
				if (x[i] == 0)
					continue;
				for (j = 0; j < i; j++)
					if (x[j] == x[i])
						break;
			} while (j < i); // Inner loop will get to j = i when x[j] != x[i] for all j
			if (i % 32 == 31)
				printf("Finished picking X coordinates for %u shares\n", i+1);
		}

when i = 0, fread return the x[i]==0, then continue to while(j<i), in this condition, the next step will go to the out for loop, then loop for the i ==1 ,to get the x[i] data from random file. This will lead to use the x[0]==0 for the following code , and this will trigger the calculateQ():CHECKSTATE(x != 0); this will absolutely a assert. So, i think this maybe a little bug. 
I've changed like this:
do {
AGAIN:	assert(fread(&x[i], sizeof(uint8_t), 1, random) == 1);
			if (x[i] == 0)
				goto AGAIN;
				//continue; BUGFIX:if x[0] ==0, the condition 'while(j<i)' is false, it jumps this loop cause j=0 and i=0, it'll lead to the x[0]=0 for the following code. 
			for (j = 0; j < i; j++)
				if (x[j] == x[i])
					break;
			} while (j < i); // Inner loop will get to j = i when x[j] != x[i] for all j
	}

**Comment by TheBlueMatt** [comment]
Indeed, no big deal indeed, will assert a bit later on. Fixed in 516104aa2dda7c609a083c8d4ff93e65a5148be5, slightly differently from your fix (just setting j to -1 initially instead).
